CREATE TABLE [dbo].[Music]
(
	[Id] INT NOT NULL IDENTiTY(1,1) PRIMARY KEY,
	[Name] varchar(30) NOT NULL,
	[ArtistId] INT NOT NULL,
	[Length] NUMERIC(5,2) NOT NULL,
	[Genre] VARCHAR(30) NOT NULL
		CHECK([Genre] IN ('Alternative Music',
                    'Blues',
                    'Classical Music',
                    'Country Music',
                    'Dance Music',
                    'Easy Music',
                    'Hip Hop / Rap',
                    'Indie Pop',
                    'Jazz',
                    'Latin Music',
                    'New Age',
                    'Opera',
                    'Pop (Popular music)',
                    'R&B / Soul',
                    'Reggae',
                    'Rock',
                    'World Music / Beats')),
	[TrackCount] INT DEFAULT 0,
	[TrackLicenses] INT DEFAULT 0,
	FOREIGN KEY ([ArtistId]) REFERENCES [Artist] ([Id]),
)